# This is a basic workflow to help you get started with Actions

name: trigger
on:
  push:
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger:
    uses: craigmilleruk/target-repo/.github/workflows/target.yml@main



